version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: bitriseio/android-ndk:v2019_11_23-08_38-b1753
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: |
              git submodule init
              git submodule update
      - run:
          name: build
          command: ndk-build
      - store_artifacts:
          path: libs
          destination: libs
